-- 1. TABLA PADRE: Los "Sobres" de las Tier Lists
create table public.tier_templates (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text,
  user_id uuid references auth.users not null,
  is_public boolean default true,
  author_name text,
  author_avatar text
);

-- 2. TABLA HIJA: Los animes dentro de cada sobre
create table public.template_items (
  id bigint generated by default as identity primary key,
  template_id bigint references public.tier_templates on delete cascade not null,
  anime_data jsonb not null,
  position integer
);

-- 3. SEGURIDAD (RLS): Reglas del juego
alter table public.tier_templates enable row level security;
alter table public.template_items enable row level security;

-- Regla 1: Ver templates públicos
create policy "Templates públicos son visibles para todos"
on public.tier_templates for select using ( true );

-- Regla 2: Ver items
create policy "Items son visibles para todos"
on public.template_items for select using ( true );

-- Regla 3: Crear templates (Solo usuarios conectados)
create policy "Usuarios pueden crear sus templates"
on public.tier_templates for insert
to authenticated
with check ( auth.uid() = user_id );

-- Regla 4: Agregar items (Solo el dueño del template)
create policy "Usuarios pueden agregar items a sus templates"
on public.template_items for insert
to authenticated
with check ( 
  exists ( 
    select 1 from public.tier_templates 
    where id = template_items.template_id 
    and user_id = auth.uid() 
  ) 
);